name: AutoMerge 🤖

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  dependabot-auto-merge:
    runs-on: ubuntu-latest

    name: Approve and ask for merge

    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - name: 🔬 Auto merge
        uses: fewlinesco/dependabot-auto-merge@v0.2.2
        with:
          github-token: ${{ secrets.GH_PAT }}
          reviewers: Meyclem Fenntasy
